proxy-providers:
  ipv6boy:
    type: http
    url: https://sub2.ipv6boy.xyz/api/v1/client/subscribe?token=4b69bb37e963c65223ca7fc803db71f0
    interval: 86400
    filter: 新加坡S1|日本|新加坡S2|新加坡10
    exclude-filter: 日本S2|日本3|日本1|2x
    exclude-type: "hysteria2"
    override:
      udp: true
      down: "1000"
      up: "1000"
      proxy-name:
      - pattern: "新加坡"
        target: "🇸🇬新加坡"
      - pattern: "日本"
        target: " 🇯🇵日本"
    path: "./proxy_provider/ipv6boy.yaml"
    health-check:
      enable: true
      interval: 300
      url: http://www.apple.com/library/test/success.html
  ipv4boy:
    type: http
    url: https://sub2.ipv6boy.xyz/api/v1/client/subscribe?token=67c3b50010f4b3b8fa29ecfa9282445c
    interval: 86400
    filter: 移动
    exclude-filter: 14
    override:
      udp: true
      down: "1000"
      up: "1000"
      proxy-name:
      - pattern: "香港"
        target: "🇭🇰香港"
    path: "./proxy_provider/ipv4boy.yaml"
    health-check:
      enable: true
      interval: 300
      url: https://cp.cloudflare.com
  backup:
    type: http
    url: https://hutaod.com/link/ce7tMRH20hsRCUXp?sub=2
    filter: 香港
    exclude-filter: 07|03|02|01|04|05
    override:
      udp: true
      additional-prefix: "🇭🇰"
      proxy-name:
      - pattern: " - IEPL - SS/SSR - "
        target: "-"
    interval: 86400
    path: "./proxy_provider/backup.yaml"
    health-check:
      enable: true
      interval: 300
      url: https://cp.cloudflare.com
  fscloud:
    type: http
    url: https://fsc.wangpankehuduan.homes/answer/land?token=7fe424e73a6b984d9b382e60d3dc27e2
    interval: 86400
    filter: 新加坡
    exclude-type: "vless|trojan"
    override:
      udp: true
      down: "1000"
      up: "1000"
      proxy-name:
      - pattern: "新加坡hy2"
        target: "🇸🇬新加坡"
      - pattern: "-移动优化"
        target: ""
    path: "./proxy_provider/fscloud.yaml"
    health-check:
      enable: true
      interval: 300
      url: http://www.apple.com/library/test/success.html


proxy-groups:
- name: proxy
  type: select
  proxies:
  - ipv6boy
  - backup
  - ipv4boy
  - manual
  - DIRECT
- name: manual
  type: select
  use:
  - ipv6boy
  - ipv4boy
  - backup
  - fscloud
- name: google
  type: select
  proxies:
  - ipv4boy
  - ipv6boy
  - manual
- name: gfw
  type: select
  proxies:
  - backup
  - ipv6boy
- name: media
  type: select
  proxies:
  - ipv6boy
  - backup
  - ipv4boy
  - manual
  - DIRECT
- name: ipv6boy
  type: url-test
  url: http://www.apple.com/library/test/success.html
  interval: 100
  tolerance: 50
  use:
  - ipv6boy
- name: ipv4boy
  type: url-test
  url: https://cp.cloudflare.com
  interval: 300
  tolerance: 50
  use:
  - ipv4boy
- name: backup
  type: url-test
  url: https://cp.cloudflare.com
  interval: 300
  tolerance: 50
  use:
  - backup
  - fscloud

rule-providers:
  google-direct:
    type: http
    behavior: domain
    format: mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/google-cn.mrs"
    path: ./ruleset/google-cn.mrs
    interval: 86400
  Telegram:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/telegramIP.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs"
    interval: 86400
  youtube:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/youtube.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/youtube.mrs"
    interval: 86400
  gfw:
    type: http
    behavior: domain
    format: mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@refs/heads/meta/geo/geosite/gfw.mrs"
    path: ./ruleset/gfw.mrs
    interval: 86400
  notcn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/wzy9024/vod@refs/heads/main/notcn.yaml"
    path: ./ruleset/notcn.yaml
    interval: 86400
  ai:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ai.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs"
    interval: 86400
  mediaip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/mediaip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/mediaip.mrs"
    interval: 86400
  media:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/media.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/media.mrs"
    interval: 86400
  microsoft-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/microsoft-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/microsoft-cn.mrs"
    interval: 86400
  apple-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/apple-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/apple-cn.mrs"
    interval: 86400
rules:
- DOMAIN-SUFFIX,ntp.org,DIRECT
- RULE-SET,ai,media
- DOMAIN-SUFFIX,bing.com,media
- DOMAIN-SUFFIX,apple.com,DIRECT
- DOMAIN-SUFFIX,icloud.com,DIRECT
- DOMAIN-SUFFIX,office.com,DIRECT
- DOMAIN-SUFFIX,windows.com,DIRECT
- DOMAIN-SUFFIX,microsoft.com,DIRECT
- RULE-SET,microsoft-cn,DIRECT
- RULE-SET,apple-cn,DIRECT
- DOMAIN-SUFFIX,creaders.net,gfw
- RULE-SET,Telegram,google,no-resolve
- RULE-SET,google-direct,DIRECT
- RULE-SET,youtube,google
- RULE-SET,mediaip,media,no-resolve
- RULE-SET,media,media
- RULE-SET,gfw,gfw
- IP-CIDR6,2404:6800::/32,google,no-resolve
- GEOIP,CN,DIRECT,no-resolve
- MATCH,proxy
